"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from envparse import env
env.read_envfile()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5y-zj9rz7*x^qv90a3!l+9$#0@ej3lw)u*%@2slk=6#aq_@wz='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', env('SERVER_IP')]

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'api',
    'jet.dashboard',
    'jet',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',from envparse import env
env.read_envfile()
]from envparse import env
env.read_envfile()
from envparse import env
env.read_envfile()
MIDDLEWARE = [from envparse import env
env.read_envfile()
    'corsheaders.middleware.CorsMifrom envparse import env
env.read_envfile()ddleware',
    'django.middleware.security.Sefrom envparse import env
env.read_envfile()curityMiddleware',
    'django.contrib.sessions.middlfrom envparse import env
env.read_envfile()eware.SessionMiddleware',
    'django.middleware.common.Commfrom envparse import env
env.read_envfile()onMiddleware',
    'django.contrib.auth.middlewarfrom envparse import env
env.read_envfile()e.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


from envparse import env
env.read_envfile()
from envparse import env
env.read_envfile()n/2.2/ref/settings/#databases
from envparse import env
env.read_envfile()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'watcher',
        'USER': 'watcher',
        'PASSWORD': 'yeshallnotpass',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

CORS_ORIGIN_WHITELIST = (
    'localhost:3000',
    '155.69.146.209:4000',
    '155.69.146.205:4000'
)

MEDIA_ROOT = env('MEDIA_ROOT', default='/home/shubham/github/asr_airflow/data/')
