# Generated by Django 2.2 on 2019-04-22 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRegistry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=4096)),
                ('status', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'metadata_registry',
            },
        ),
    ]
