# Generated by Django 2.2 on 2019-05-10 04:08

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=256)),
                ('pipeline_id', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('pipeline', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'metadata_registry',
            },
        ),
    ]
