# Generated by Django 2.2 on 2019-04-22 04:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataregistry',
            name='filename',
        ),
        migrations.AddField(
            model_name='metadataregistry',
            name='pipeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
