# Generated by Django 2.2 on 2019-04-22 04:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190422_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataregistry',
            name='pipeline',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
