# Generated by Django 2.2 on 2019-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190422_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataregistry',
            name='pipeline_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='metadataregistry',
            name='recording_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
