# Generated by Django 2.2 on 2019-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190422_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataregistry',
            name='pipeline_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='metadataregistry',
            name='recording_id',
            field=models.CharField(max_length=256),
        ),
    ]
